package ins.platform.saa.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SaaRole
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SAA_ROLE")
public class SaaRole implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String roleCode;
	private Integer version;
	private String roleCName;
	private String roleTName;
	private String roleEName;
	private String comCode;
	private String creatorCode;
	private Date createTime;
	private String updaterCode;
	private Date updateTime;
	private String validInd;
	private String remark;
	private String flag;
	private Date insertTimeForHis;
	private Date operateTimeForHis;
	private List<SaaUserRole> saaUserRoles = new ArrayList<SaaUserRole>(0);
	private List<SaaRoleTask> saaRoleTasks = new ArrayList<SaaRoleTask>(0);
	@Id
	@Column(name = "ROLE_CODE", unique = true, nullable = false, length=64)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}
	@Version
	@Column(name = "VERSION", nullable = false, precision=9, scale=0)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	@Column(name = "ROLE_C_NAME", length=60)
	public String getRoleCName() {
		return this.roleCName;
	}

	public void setRoleCName(String roleCName) {
		this.roleCName = roleCName;
	}
	@Column(name = "ROLE_T_NAME", length=60)
	public String getRoleTName() {
		return this.roleTName;
	}

	public void setRoleTName(String roleTName) {
		this.roleTName = roleTName;
	}
	@Column(name = "ROLE_E_NAME", length=60)
	public String getRoleEName() {
		return this.roleEName;
	}

	public void setRoleEName(String roleEName) {
		this.roleEName = roleEName;
	}
	@Column(name = "COMCODE", nullable = false, length=8)
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}
	@Column(name = "CREATOR_CODE", length=10)
	public String getCreatorCode() {
		return this.creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length=7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	@Column(name = "UPDATER_CODE", length=10)
	public String getUpdaterCode() {
		return this.updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length=7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	@Column(name = "VALID_IND", nullable = false, length=1)
	public String getValidInd() {
		return this.validInd;
	}

	public void setValidInd(String validInd) {
		this.validInd = validInd;
	}
	@Column(name = "REMARK", length=60)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Column(name = "FLAG", length=2)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERT_TIME_FOR_HIS",insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OPERATE_TIME_FOR_HIS",insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="saaRole")
	public List<SaaUserRole> getSaaUserRoles() {
		return this.saaUserRoles;
	}

	public void setSaaUserRoles(List<SaaUserRole> saaUserRoles) {
		this.saaUserRoles = saaUserRoles;
	}
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="saaRole")
	public List<SaaRoleTask> getSaaRoleTasks() {
		return this.saaRoleTasks;
	}

	public void setSaaRoleTasks(List<SaaRoleTask> saaRoleTasks) {
		this.saaRoleTasks = saaRoleTasks;
	}
}
