package ins.platform.saa.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SaaTask
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SAA_TASK")
public class SaaTask implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String taskCode;
	private Integer version;
	private String groupName;
	private String taskCName;
	private String taskTName;
	private String taskEName;
	private String url;
	private String creatorCode;
	private Date createTime;
	private String updaterCode;
	private Date updateTime;
	private String validInd;
	private String remark;
	private String flag;
	private Date insertTimeForHis;
	private Date operateTimeForHis;
	private List<SaaRoleTask> saaRoleTasks = new ArrayList<SaaRoleTask>(0);
	@Id
	@Column(name = "TASK_CODE", unique = true, nullable = false, length=60)
	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}
	@Version
	@Column(name = "VERSION", nullable = false, precision=9, scale=0)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	@Column(name = "GROUP_NAME", nullable = false, length=120)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
	@Column(name = "TASK_C_NAME", length=60)
	public String getTaskCName() {
		return this.taskCName;
	}

	public void setTaskCName(String taskCName) {
		this.taskCName = taskCName;
	}
	@Column(name = "TASK_T_NAME", length=60)
	public String getTaskTName() {
		return this.taskTName;
	}

	public void setTaskTName(String taskTName) {
		this.taskTName = taskTName;
	}
	@Column(name = "TASK_E_NAME", length=60)
	public String getTaskEName() {
		return this.taskEName;
	}

	public void setTaskEName(String taskEName) {
		this.taskEName = taskEName;
	}
	@Column(name = "URL", nullable = false, length=200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	@Column(name = "CREATOR_CODE", length=60)
	public String getCreatorCode() {
		return this.creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length=7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	@Column(name = "UPDATER_CODE", length=60)
	public String getUpdaterCode() {
		return this.updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length=7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	@Column(name = "VALIDIND", nullable = false, length=1)
	public String getValidInd() {
		return this.validInd;
	}

	public void setValidInd(String validInd) {
		this.validInd = validInd;
	}
	@Column(name = "REMARK", length=60)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Column(name = "FLAG", length=2)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERT_TIME_FOR_HIS",insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OPERATE_TIME_FOR_HIS",insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="saaTask")
	public List<SaaRoleTask> getSaaRoleTasks() {
		return this.saaRoleTasks;
	}

	public void setSaaRoleTasks(List<SaaRoleTask> saaRoleTasks) {
		this.saaRoleTasks = saaRoleTasks;
	}
}
