CREATE TABLE msg_info (
  Id bigint(18) not null AUTO_INCREMENT,
  Sender varchar(40) NOT NULL,
  Receiver varchar(1024) NOT NULL,
  Send_Time datetime NOT NULL,
  Repeat_Cycle decimal(10,0) ,
  Content text,
  User_Code varchar(40) ,
  Com_Code varchar(40) ,
  System_Code varchar(40) ,
  Additional_Code varchar(80) ,
  Msg_Type varchar(20) ,
  Error_Log text,
  Business_Type varchar(40) ,
  Status varchar(20) NOT NULL,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_msg_info PRIMARY KEY (Id)
);
CREATE TABLE msg_info_custom (
  Id bigint(18) not null AUTO_INCREMENT,
  User_Code varchar(64) ,
  Email_Flag_Cla varchar(64) ,
  Sta_Letter_Flag_Cla varchar(64) ,
  Sms_Flag_Cla varchar(64) ,
  Email_Flag_Reg varchar(64) ,
  Sta_Letter_Flag_Reg varchar(64) ,
  Sms_Flag_Reg varchar(64) ,
  Email_Address varchar(64) ,
  Phone_No varchar(20) ,
  Msg_Type varchar(20) ,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_msg_info_custom PRIMARY KEY (Id)
);
CREATE TABLE msg_info_his (
  Id bigint(18) not null AUTO_INCREMENT,
  U_U_Id varchar(255) NOT NULL,
  Sender varchar(40) NOT NULL,
  Receiver varchar(1024) NOT NULL,
  Send_Time datetime NOT NULL,
  Repeat_Cycle decimal(10,0) ,
  Content text,
  User_Code varchar(40) ,
  Com_Code varchar(40) ,
  System_Code varchar(40) ,
  Additional_Code varchar(80) ,
  Msg_Type varchar(20) ,
  Error_Log text,
  Business_Type varchar(40) ,
  Status varchar(20) NOT NULL,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_msg_info_his PRIMARY KEY (Id)
);
CREATE TABLE sdd_type (
  Type varchar(250) not null ,
  Type_Desc varchar(250) ,
  New_Type varchar(250),
  Valid_Status varchar(1) ,
  Flag varchar(45) ,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_sdd_type PRIMARY KEY (Type)
);
CREATE TABLE sdd_code (
  Id bigint(18) not null AUTO_INCREMENT,
  Type varchar(250) ,
  Code varchar(250) ,
  Value varchar(250),
  CN_Name varchar(250) ,
  Full_Name varchar(250) ,
  ENG_Name varchar(250) ,
  New_Code varchar(250) ,
  Code_Desc varchar(250) ,
  SERIAL_NO bigint(4) DEFAULT NULL,
  Valid_Status varchar(1) ,
  Flag varchar(2) ,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_sdd_code PRIMARY KEY (Id),
  constraint FK_sdd_type FOREIGN KEY (Type) REFERENCES sdd_type (Type)
) ;
CREATE TABLE smc_menu (
  Id bigint(18) not null AUTO_INCREMENT,
  Upper_Id bigint(18) not null,
  Menu_Level bigint(9) NOT NULL,
  System_Code varchar(255) ,
  Menu_CName varchar(255) ,
  Menu_TName varchar(255) ,
  Menu_EName varchar(255) ,
  Action_Url varchar(255) ,
  Target varchar(255) ,
  Display_No bigint(9) NOT NULL,
  Image varchar(255) ,
  Image_Expand varchar(255) ,
  Image_Collapse varchar(255) ,
  Icon_Expand varchar(255) ,
  Icon_Collapse varchar(255) ,
  Task_Code varchar(255) ,
  Creator_Code varchar(10) ,
  Create_Time datetime ,
  Updater_Code varchar(10) ,
  Update_Time datetime ,
  Valid_Ind varchar(1) NOT NULL,
  Remark varchar(255) ,
  Flag varchar(255) ,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  style varchar(250) ,
  CONSTRAINT PK_smc_menu PRIMARY KEY (Id),
  CONSTRAINT idx_utimenu_idcode unique(Id,Upper_Id,System_Code,Display_No,Valid_Ind)
);
CREATE TABLE sta_letter (
  Id bigint(18) not null AUTO_INCREMENT,
  User_Code varchar(64) ,
  Receiver varchar(64) NOT NULL,
  Content varchar(255) ,
  Theme varchar(64) ,
  Send_Time datetime ,
  Receive_Time datetime ,
  Sender varchar(64) ,
  Read_Flag varchar(2) ,
  Valid_Flag_Rec varchar(2) ,
  Valid_Flag_Send varchar(2) ,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_sta_letter PRIMARY KEY (Id)
);
CREATE TABLE sys_application (
  Id bigint(18) not null AUTO_INCREMENT,
  system_code varchar(255) NOT NULL,
  cname varchar(255) ,
  ename varchar(255) ,
  description varchar(255) ,
  deleted_flag BINARY(1) ,
  home_Url varchar(255) ,
  tech_architecture varchar(255) ,
  developent_team varchar(255) ,
  online_time datetime ,
  owner varchar(255) ,
  backup_owner varchar(255) ,
  database_name varchar(255) ,
  database_type varchar(255) ,
  dbserver_path varchar(255) ,
  svn_path varchar(255) ,
  created_user varchar(255) ,
  created_date datetime ,
  updated_user varchar(255) ,
  updated_date datetime ,
  validate_type varchar(255) ,
  login_options varchar(1000) ,
  add_role BINARY(1) ,
  role_auth BINARY(1) ,
  res_auth BINARY(1) ,
  store_dept_auth BINARY(1) ,
  group_auth BINARY(1) ,
  store_owner BINARY(1) ,
  app_lock BINARY(1) ,
  constraint PK_sys_application PRIMARY KEY (Id),
  constraint sys_application_ix1 unique(system_code)
);

CREATE TABLE sys_area_dict (
  AREA_CODE varchar(20) NOT NULL,
  AREA_NAME varchar(3000) ,
  SHORT_CODE varchar(20) ,
  FULL_NAME varchar(3000) ,
  AREA_LEVEL decimal(3,1) ,
  SERIAL_NO decimal(4,0) ,
  UPPER_CODE varchar(20) ,
  POST_CODE varchar(20) ,
  IS_VALID varchar(1) ,
  REMARK varchar(1000) ,
  OFTEN_FLAG varchar(2) ,
  PRIMARY KEY (AREA_CODE)
);
CREATE TABLE sys_cas_login (
  Id bigint(18) not null AUTO_INCREMENT,
  created_date datetime DEFAULT NULL,
  updated_date datetime DEFAULT NULL,
  username varchar(255) DEFAULT NULL,
  ticket varchar(255) DEFAULT NULL,
  sticket varchar(255) DEFAULT NULL,
  action varchar(255) DEFAULT NULL,
  client_ip varchar(255) DEFAULT NULL,
  server_ip varchar(255) DEFAULT NULL,
  login_time datetime DEFAULT NULL,
  logout_time datetime DEFAULT NULL,
  constraint PK_sys_cas_login PRIMARY KEY (Id)
);
CREATE TABLE sys_trans_config (
  TRANS_TYPE varchar(30) NOT NULL,
  TRANS_NAME varchar(50) ,
  SELECT_TABLE varchar(30) ,
  SELECT_CODE varchar(30) ,
  SELECT_NAME varchar(50) ,
  SELECT_WHERE varchar(100) ,
  PARARM_VALUE varchar(255) ,
  ORDER_BY varchar(30) ,
  REMARK varchar(100) ,
  PRIMARY KEY (TRANS_TYPE)
);
CREATE TABLE sys_user (
  Id bigint(18) not null AUTO_INCREMENT,
  user_code varchar(60) NOT NULL,
  user_name varchar(60) ,
  email varchar(60) ,
  mobile_phone varchar(20) ,
  password varchar(32) NOT NULL,
  salt varchar(10)  DEFAULT '0' NOT NULL,
  second_validate varchar(1) ,
  ga_code varchar(60) ,
  question varchar(255) ,
  answer varchar(255) ,
  sex varchar(1) ,
  birthday datetime ,
  reg_time datetime ,
  last_login_failed bigint(10) ,
  last_time datetime ,
  last_ip varchar(15) ,
  msn varchar(60) ,
  qq varchar(20) ,
  office_phone varchar(20) ,
  home_phone varchar(20) ,
  checked varchar(1) DEFAULT '0' NOT NULL,
  age varchar(60) ,
  Operators varchar(60) ,
  PASSWORD_SET_DATE datetime ,
  PASSWORD_EXPIRE_DATE datetime ,
  ADDRESS varchar(60) ,
  POSTCODE varchar(6) ,
  VALID_STATUS varchar(1) ,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_sys_user PRIMARY KEY (Id),
  constraint user_code unique(user_code)
);
create index email on sys_user(email);
create index mobile_phone on sys_user(mobile_phone);
CREATE TABLE sys_user_property (
  id bigint(18) NOT NULL,
  User_Code varchar(60) NOT NULL,
  Code varchar(22) NOT NULL,
  Value varchar(8) NOT NULL,
  Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_sys_user_property PRIMARY KEY (id)
);
CREATE TABLE sys_user_run_as (
  Id bigint(18) not null AUTO_INCREMENT,
  from_user_code varchar(60) NOT NULL,
  to_user_code varchar(60) NOT NULL,
   Version bigint(9) NOT NULL,
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint seq_sys_user_run_as PRIMARY KEY (id)
);
create table SYS_COMPANY
(
  Id                bigint(18) NOT NULL,
  com_code          VARCHAR(8) not null,
  com_path          VARCHAR(500) not null,
  com_cname          VARCHAR(250) not null,
  com_ename          VARCHAR(250),
  address_cname      VARCHAR(250),
  address_ename      VARCHAR(250),
  post_code          VARCHAR(6),
  phone_number       VARCHAR(30),
  fax_number         VARCHAR(20),
  upper_com_code      VARCHAR(8),
  insurer_name       VARCHAR(250),
  com_type           VARCHAR(1),
  manager           VARCHAR(40),
  accountant        VARCHAR(40),
  remark            VARCHAR(40),
  new_com_code        VARCHAR(8) not null,
  valid_status       VARCHAR(1) not null,
  acnt_unit          VARCHAR(8),
  article_code       VARCHAR(30),
  flag              VARCHAR(10),
  Insert_Time_For_His timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Operate_Time_For_His datetime,
  constraint PK_DCOMPANY primary key (ID)
);
create table PDFC_SERVER
(
  id        VARCHAR(18) not null,
  host_name VARCHAR(255),
  os        VARCHAR(255),
  cpu       number(3),
  mem       number(3),
  hd        number(6),
  hd_info   VARCHAR(255),
  ip        VARCHAR(255),
  remark    VARCHAR(255),
  constraint PDFC_SERVER primary key (ID)
);





