package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SmcMenu
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SMC_MENU", uniqueConstraints = @UniqueConstraint(columnNames={"ID", "UPPER_ID", "SYSTEM_CODE", "DISPLAY_NO", "VALID_IND"}) 
)
public class SmcMenu implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Integer version;
	private Long upperId;
	private Integer menuLevel;
	private String systemCode;
	private String menuCName;
	private String menuTName;
	private String menuEName;
	private String actionURL;
	private String target;
	private Integer displayNo;
	private String image;
	private String imageExpand;
	private String imageCollapse;
	private String iconExpand;
	private String iconCollapse;
	private String taskCode;
	private String creatorCode;
	private Date createTime;
	private String updaterCode;
	private Date updateTime;
	private String validInd;
	private String remark;
	private String flag;
	private Date insertTimeForHis;
	private Date operateTimeForHis;
	private String style;
	@Id
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator", strategy = "native")
	
	@Column(name = "ID", unique = true, nullable = false, precision=18, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Version
	@Column(name = "VERSION", nullable = false, precision=9, scale=0)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	@Column(name = "UPPER_ID", nullable = false, precision=18, scale=0)
	public Long getUpperId() {
		return this.upperId;
	}

	public void setUpperId(Long upperId) {
		this.upperId = upperId;
	}
	@Column(name = "MENU_LEVEL", nullable = false, precision=9, scale=0)
	public Integer getMenuLevel() {
		return this.menuLevel;
	}

	public void setMenuLevel(Integer menuLevel) {
		this.menuLevel = menuLevel;
	}
	@Column(name = "SYSTEM_CODE")
	public String getSystemCode() {
		return this.systemCode;
	}

	public void setSystemCode(String systemCode) {
		this.systemCode = systemCode;
	}
	@Column(name = "MENU_CNAME")
	public String getMenuCName() {
		return this.menuCName;
	}

	public void setMenuCName(String menuCName) {
		this.menuCName = menuCName;
	}
	@Column(name = "MENU_TNAME")
	public String getMenuTName() {
		return this.menuTName;
	}

	public void setMenuTName(String menuTName) {
		this.menuTName = menuTName;
	}
	@Column(name = "MENU_ENAME")
	public String getMenuEName() {
		return this.menuEName;
	}

	public void setMenuEName(String menuEName) {
		this.menuEName = menuEName;
	}
	@Column(name = "ACTION_URL")
	public String getActionURL() {
		return this.actionURL;
	}

	public void setActionURL(String actionURL) {
		this.actionURL = actionURL;
	}
	@Column(name = "TARGET")
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}
	@Column(name = "DISPLAY_NO", nullable = false, precision=9, scale=0)
	public Integer getDisplayNo() {
		return this.displayNo;
	}

	public void setDisplayNo(Integer displayNo) {
		this.displayNo = displayNo;
	}
	@Column(name = "IMAGE")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	@Column(name = "IMAGE_EXPAND")
	public String getImageExpand() {
		return this.imageExpand;
	}

	public void setImageExpand(String imageExpand) {
		this.imageExpand = imageExpand;
	}
	@Column(name = "IMAGE_COLLAPSE")
	public String getImageCollapse() {
		return this.imageCollapse;
	}

	public void setImageCollapse(String imageCollapse) {
		this.imageCollapse = imageCollapse;
	}
	@Column(name = "ICON_EXPAND")
	public String getIconExpand() {
		return this.iconExpand;
	}

	public void setIconExpand(String iconExpand) {
		this.iconExpand = iconExpand;
	}
	@Column(name = "ICON_COLLAPSE")
	public String getIconCollapse() {
		return this.iconCollapse;
	}

	public void setIconCollapse(String iconCollapse) {
		this.iconCollapse = iconCollapse;
	}
	@Column(name = "TASK_CODE")
	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}
	@Column(name = "CREATOR_CODE", length=10)
	public String getCreatorCode() {
		return this.creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length=7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	@Column(name = "UPDATER_CODE", length=10)
	public String getUpdaterCode() {
		return this.updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length=7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	@Column(name = "VALID_IND", nullable = false, length=1)
	public String getValidInd() {
		return this.validInd;
	}

	public void setValidInd(String validInd) {
		this.validInd = validInd;
	}
	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Column(name = "FLAG")
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERT_TIME_FOR_HIS",insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OPERATE_TIME_FOR_HIS",insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
	@Column(name = "STYLE", length=250)
	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}
}
