package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SysApplication
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SYS_APPLICATION", uniqueConstraints = @UniqueConstraint(columnNames="SYSTEM_CODE") 
)
public class SysApplication implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String systemCode;
	private String cname;
	private String ename;
	private String description;
	private byte[] deletedFlag;
	private String homeUrl;
	private String techArchitecture;
	private String developentTeam;
	private Date onlineTime;
	private String owner;
	private String backupOwner;
	private String databaseName;
	private String databaseType;
	private String dbserverPath;
	private String svnPath;
	private String createdUser;
	private Date createdDate;
	private String updatedUser;
	private Date updatedDate;
	private String validateType;
	private String loginOptions;
	private byte[] addRole;
	private byte[] roleAuth;
	private byte[] resAuth;
	private byte[] storeDeptAuth;
	private byte[] groupAuth;
	private byte[] storeOwner;
	private byte[] appLock;
	@Id
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator", strategy = "native")
	
	@Column(name = "ID", unique = true, nullable = false, precision=18, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "SYSTEM_CODE", unique = true, nullable = false)
	public String getSystemCode() {
		return this.systemCode;
	}

	public void setSystemCode(String systemCode) {
		this.systemCode = systemCode;
	}
	@Column(name = "CNAME")
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}
	@Column(name = "ENAME")
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}
	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Column(name = "DELETED_FLAG")
	public byte[] getDeletedFlag() {
		return this.deletedFlag;
	}

	public void setDeletedFlag(byte[] deletedFlag) {
		this.deletedFlag = deletedFlag;
	}
	@Column(name = "HOME_URL")
	public String getHomeUrl() {
		return this.homeUrl;
	}

	public void setHomeUrl(String homeUrl) {
		this.homeUrl = homeUrl;
	}
	@Column(name = "TECH_ARCHITECTURE")
	public String getTechArchitecture() {
		return this.techArchitecture;
	}

	public void setTechArchitecture(String techArchitecture) {
		this.techArchitecture = techArchitecture;
	}
	@Column(name = "DEVELOPENT_TEAM")
	public String getDevelopentTeam() {
		return this.developentTeam;
	}

	public void setDevelopentTeam(String developentTeam) {
		this.developentTeam = developentTeam;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ONLINE_TIME", length=7)
	public Date getOnlineTime() {
		return this.onlineTime;
	}

	public void setOnlineTime(Date onlineTime) {
		this.onlineTime = onlineTime;
	}
	@Column(name = "OWNER")
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}
	@Column(name = "BACKUP_OWNER")
	public String getBackupOwner() {
		return this.backupOwner;
	}

	public void setBackupOwner(String backupOwner) {
		this.backupOwner = backupOwner;
	}
	@Column(name = "DATABASE_NAME")
	public String getDatabaseName() {
		return this.databaseName;
	}

	public void setDatabaseName(String databaseName) {
		this.databaseName = databaseName;
	}
	@Column(name = "DATABASE_TYPE")
	public String getDatabaseType() {
		return this.databaseType;
	}

	public void setDatabaseType(String databaseType) {
		this.databaseType = databaseType;
	}
	@Column(name = "DBSERVER_PATH")
	public String getDbserverPath() {
		return this.dbserverPath;
	}

	public void setDbserverPath(String dbserverPath) {
		this.dbserverPath = dbserverPath;
	}
	@Column(name = "SVN_PATH")
	public String getSvnPath() {
		return this.svnPath;
	}

	public void setSvnPath(String svnPath) {
		this.svnPath = svnPath;
	}
	@Column(name = "CREATED_USER")
	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length=7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	@Column(name = "UPDATED_USER")
	public String getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(String updatedUser) {
		this.updatedUser = updatedUser;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length=7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	@Column(name = "VALIDATE_TYPE")
	public String getValidateType() {
		return this.validateType;
	}

	public void setValidateType(String validateType) {
		this.validateType = validateType;
	}
	@Column(name = "LOGIN_OPTIONS", length=1000)
	public String getLoginOptions() {
		return this.loginOptions;
	}

	public void setLoginOptions(String loginOptions) {
		this.loginOptions = loginOptions;
	}
	@Column(name = "ADD_ROLE")
	public byte[] getAddRole() {
		return this.addRole;
	}

	public void setAddRole(byte[] addRole) {
		this.addRole = addRole;
	}
	@Column(name = "ROLE_AUTH")
	public byte[] getRoleAuth() {
		return this.roleAuth;
	}

	public void setRoleAuth(byte[] roleAuth) {
		this.roleAuth = roleAuth;
	}
	@Column(name = "RES_AUTH")
	public byte[] getResAuth() {
		return this.resAuth;
	}

	public void setResAuth(byte[] resAuth) {
		this.resAuth = resAuth;
	}
	@Column(name = "STORE_DEPT_AUTH")
	public byte[] getStoreDeptAuth() {
		return this.storeDeptAuth;
	}

	public void setStoreDeptAuth(byte[] storeDeptAuth) {
		this.storeDeptAuth = storeDeptAuth;
	}
	@Column(name = "GROUP_AUTH")
	public byte[] getGroupAuth() {
		return this.groupAuth;
	}

	public void setGroupAuth(byte[] groupAuth) {
		this.groupAuth = groupAuth;
	}
	@Column(name = "STORE_OWNER")
	public byte[] getStoreOwner() {
		return this.storeOwner;
	}

	public void setStoreOwner(byte[] storeOwner) {
		this.storeOwner = storeOwner;
	}
	@Column(name = "APP_LOCK")
	public byte[] getAppLock() {
		return this.appLock;
	}

	public void setAppLock(byte[] appLock) {
		this.appLock = appLock;
	}
}
