package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SysAreaDict
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SYS_AREA_DICT")
public class SysAreaDict implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String areaCode;
	private String areaName;
	private String shortCode;
	private String fullName;
	private BigDecimal areaLevel;
	private Short serialNo;
	private String upperCode;
	private String postCode;
	private String isValid;
	private String remark;
	private String oftenFlag;
	@Id
	@Column(name = "AREA_CODE", unique = true, nullable = false, length=20)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}
	@Column(name = "AREA_NAME", length=3000)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}
	@Column(name = "SHORT_CODE", length=20)
	public String getShortCode() {
		return this.shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}
	@Column(name = "FULL_NAME", length=3000)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	@Column(name = "AREA_LEVEL", precision=3, scale=1)
	public BigDecimal getAreaLevel() {
		return this.areaLevel;
	}

	public void setAreaLevel(BigDecimal areaLevel) {
		this.areaLevel = areaLevel;
	}
	@Column(name = "SERIAL_NO", precision=4, scale=0)
	public Short getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Short serialNo) {
		this.serialNo = serialNo;
	}
	@Column(name = "UPPER_CODE", length=20)
	public String getUpperCode() {
		return this.upperCode;
	}

	public void setUpperCode(String upperCode) {
		this.upperCode = upperCode;
	}
	@Column(name = "POST_CODE", length=20)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}
	@Column(name = "IS_VALID", length=1)
	public String getIsValid() {
		return this.isValid;
	}

	public void setIsValid(String isValid) {
		this.isValid = isValid;
	}
	@Column(name = "REMARK", length=1000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Column(name = "OFTEN_FLAG", length=2)
	public String getOftenFlag() {
		return this.oftenFlag;
	}

	public void setOftenFlag(String oftenFlag) {
		this.oftenFlag = oftenFlag;
	}
}
