package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * POJO Class SysCompanyUserId
 */
@Embeddable
public class SysCompanyUserId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long userId;
	private Long groupID;
	@Column(name = "USER_ID", nullable = false, precision=18, scale=0)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}
	@Column(name = "GROUP_ID", nullable = false, precision=18, scale=0)
	public Long getGroupID() {
		return this.groupID;
	}

	public void setGroupID(Long groupID) {
		this.groupID = groupID;
	}
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		
		if (!(other instanceof SysCompanyUserId)) {
			return false;
		}
		SysCompanyUserId castOther = (SysCompanyUserId) other;  
		return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getGroupID()==castOther.getGroupID()) || ( this.getGroupID()!=null && castOther.getGroupID()!=null && this.getGroupID().equals(castOther.getGroupID()) ) );
	}
   
	public int hashCode() {
		int result = 17;         
		result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
		result = 37 * result + ( getGroupID() == null ? 0 : this.getGroupID().hashCode() );
		return result;
   }   
}
