package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SysCompanyUser
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SYS_COMPANY_USER", uniqueConstraints = @UniqueConstraint(columnNames={"GROUP_ID", "USER_ID"}) 
)
public class SysCompanyUser implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private SysCompanyUserId id;
	@EmbeddedId
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator", strategy = "native")
	
	@AttributeOverrides( {
        @AttributeOverride(name = "USERID", column = @Column(name = "USER_ID", nullable = false, precision=18, scale=0) ), 
        @AttributeOverride(name = "GROUPID", column = @Column(name = "GROUP_ID", nullable = false, precision=18, scale=0) ) } )
	public SysCompanyUserId getId() {
		return this.id;
	}

	public void setId(SysCompanyUserId id) {
		this.id = id;
	}
}
