package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SysCompany
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SYS_COMPANY")
public class SysCompany implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String comCode;
	private String comPath;
	private String comCName;
	private String comEName;
	private String addressCName;
	private String addressEName;
	private String postCode;
	private String phoneNumber;
	private String faxNumber;
	private String upperComCode;
	private String insurerName;
	private String comType;
	private String manager;
	private String accountant;
	private String remark;
	private String newComCode;
	private String validStatus;
	private String acntUnit;
	private String articleCode;
	private String flag;
	private Date insertTimeForHis;
	private Date operateTimeForHis;
	@Id
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator", strategy = "native")
	
	@Column(name = "ID", unique = true, nullable = false, precision=18, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "COM_CODE", nullable = false, length=8)
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}
	@Column(name = "COM_PATH", nullable = false, length=500)
	public String getComPath() {
		return this.comPath;
	}

	public void setComPath(String comPath) {
		this.comPath = comPath;
	}
	@Column(name = "COM_CNAME", nullable = false, length=250)
	public String getComCName() {
		return this.comCName;
	}

	public void setComCName(String comCName) {
		this.comCName = comCName;
	}
	@Column(name = "COM_ENAME", length=250)
	public String getComEName() {
		return this.comEName;
	}

	public void setComEName(String comEName) {
		this.comEName = comEName;
	}
	@Column(name = "ADDRESS_CNAME", length=250)
	public String getAddressCName() {
		return this.addressCName;
	}

	public void setAddressCName(String addressCName) {
		this.addressCName = addressCName;
	}
	@Column(name = "ADDRESS_ENAME", length=250)
	public String getAddressEName() {
		return this.addressEName;
	}

	public void setAddressEName(String addressEName) {
		this.addressEName = addressEName;
	}
	@Column(name = "POST_CODE", length=6)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}
	@Column(name = "PHONE_NUMBER", length=30)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	@Column(name = "FAX_NUMBER", length=20)
	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}
	@Column(name = "UPPER_COM_CODE", length=8)
	public String getUpperComCode() {
		return this.upperComCode;
	}

	public void setUpperComCode(String upperComCode) {
		this.upperComCode = upperComCode;
	}
	@Column(name = "INSURER_NAME", length=250)
	public String getInsurerName() {
		return this.insurerName;
	}

	public void setInsurerName(String insurerName) {
		this.insurerName = insurerName;
	}
	@Column(name = "COM_TYPE", length=1)
	public String getComType() {
		return this.comType;
	}

	public void setComType(String comType) {
		this.comType = comType;
	}
	@Column(name = "MANAGER", length=40)
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}
	@Column(name = "ACCOUNTANT", length=40)
	public String getAccountant() {
		return this.accountant;
	}

	public void setAccountant(String accountant) {
		this.accountant = accountant;
	}
	@Column(name = "REMARK", length=40)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Column(name = "NEW_COM_CODE", nullable = false, length=8)
	public String getNewComCode() {
		return this.newComCode;
	}

	public void setNewComCode(String newComCode) {
		this.newComCode = newComCode;
	}
	@Column(name = "VALID_STATUS", nullable = false, length=1)
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}
	@Column(name = "ACNT_UNIT", length=8)
	public String getAcntUnit() {
		return this.acntUnit;
	}

	public void setAcntUnit(String acntUnit) {
		this.acntUnit = acntUnit;
	}
	@Column(name = "ARTICLE_CODE", length=30)
	public String getArticleCode() {
		return this.articleCode;
	}

	public void setArticleCode(String articleCode) {
		this.articleCode = articleCode;
	}
	@Column(name = "FLAG", length=10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERT_TIME_FOR_HIS",insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OPERATE_TIME_FOR_HIS",insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
}
