package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * POJO Class SysCodeDictId
 */
@Embeddable
public class SysCodeDictId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String codeType;
	private String codeCode;
	@Column(name = "CODE_TYPE", nullable = false, length=30)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}
	@Column(name = "CODE_CODE", nullable = false, length=20)
	public String getCodeCode() {
		return this.codeCode;
	}

	public void setCodeCode(String codeCode) {
		this.codeCode = codeCode;
	}
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		
		if (!(other instanceof SysCodeDictId)) {
			return false;
		}
		SysCodeDictId castOther = (SysCodeDictId) other;  
		return ( (this.getCodeType()==castOther.getCodeType()) || ( this.getCodeType()!=null && castOther.getCodeType()!=null && this.getCodeType().equals(castOther.getCodeType()) ) )
 && ( (this.getCodeCode()==castOther.getCodeCode()) || ( this.getCodeCode()!=null && castOther.getCodeCode()!=null && this.getCodeCode().equals(castOther.getCodeCode()) ) );
	}
   
	public int hashCode() {
		int result = 17;         
		result = 37 * result + ( getCodeType() == null ? 0 : this.getCodeType().hashCode() );
		result = 37 * result + ( getCodeCode() == null ? 0 : this.getCodeCode().hashCode() );
		return result;
   }   
}
