package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SysCodeDict
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SYS_CODE_DICT")
public class SysCodeDict implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private SysCodeDictId id;
	private String codeName;
	private String fullName;
	private String engName;
	private Short serialNo;
	private String upperCode;
	private String isValid;
	private String isRoot;
	private String remark;
	private String property1;
	private String property2;
	private String property3;
	@EmbeddedId	
	@AttributeOverrides( {
        @AttributeOverride(name = "CODETYPE", column = @Column(name = "CODE_TYPE", nullable = false, length=30) ), 
        @AttributeOverride(name = "CODECODE", column = @Column(name = "CODE_CODE", nullable = false, length=20) ) } )
	public SysCodeDictId getId() {
		return this.id;
	}

	public void setId(SysCodeDictId id) {
		this.id = id;
	}
	@Column(name = "CODE_NAME")
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}
	@Column(name = "FULL_NAME")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}
	@Column(name = "ENGNAME")
	public String getEngName() {
		return this.engName;
	}

	public void setEngName(String engName) {
		this.engName = engName;
	}
	@Column(name = "SERIAL_NO", precision=4, scale=0)
	public Short getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Short serialNo) {
		this.serialNo = serialNo;
	}
	@Column(name = "UPPER_CODE", length=20)
	public String getUpperCode() {
		return this.upperCode;
	}

	public void setUpperCode(String upperCode) {
		this.upperCode = upperCode;
	}
	@Column(name = "IS_VALID", length=1)
	public String getIsValid() {
		return this.isValid;
	}

	public void setIsValid(String isValid) {
		this.isValid = isValid;
	}
	@Column(name = "IS_ROOT", length=1)
	public String getIsRoot() {
		return this.isRoot;
	}

	public void setIsRoot(String isRoot) {
		this.isRoot = isRoot;
	}
	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Column(name = "PROPERTY1", length=20)
	public String getProperty1() {
		return this.property1;
	}

	public void setProperty1(String property1) {
		this.property1 = property1;
	}
	@Column(name = "PROPERTY2", length=20)
	public String getProperty2() {
		return this.property2;
	}

	public void setProperty2(String property2) {
		this.property2 = property2;
	}
	@Column(name = "PROPERTY3", length=20)
	public String getProperty3() {
		return this.property3;
	}

	public void setProperty3(String property3) {
		this.property3 = property3;
	}
}
