package ins.platform.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class SysUser
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "SYS_USER", uniqueConstraints = @UniqueConstraint(columnNames="USER_CODE") 
)
public class SysUser implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Integer version;
	private String userCode;
	private String userName;
	private String email;
	private String mobilePhone;
	private String password;
	private String salt;
	private String secondValidate;
	private String gaCode;
	private String question;
	private String answer;
	private String sex;
	private Date birthday;
	private Date regTime;
	private Long lastLoginFailed;
	private Date lastTime;
	private String lastIp;
	private String msn;
	private String qq;
	private String officePhone;
	private String homePhone;
	private String checked;
	private String age;
	private String operators;
	private Date passwordSetDate;
	private Date passwordExpireDate;
	private String address;
	private String postCode;
	private String validStatus;
	private Date insertTimeForHis;
	private Date operateTimeForHis;
	@Id
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator", strategy = "native")
	
	@Column(name = "ID", unique = true, nullable = false, precision=18, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Version
	@Column(name = "VERSION", nullable = false, precision=9, scale=0)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	@Column(name = "USER_CODE", unique = true, nullable = false, length=60)
	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}
	@Column(name = "USER_NAME", length=60)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	@Column(name = "EMAIL", length=60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@Column(name = "MOBILE_PHONE", length=20)
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}
	@Column(name = "PASSWORD", nullable = false, length=32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name = "SALT", nullable = false, length=10)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}
	@Column(name = "SECOND_VALIDATE", length=1)
	public String getSecondValidate() {
		return this.secondValidate;
	}

	public void setSecondValidate(String secondValidate) {
		this.secondValidate = secondValidate;
	}
	@Column(name = "GA_CODE", length=60)
	public String getGaCode() {
		return this.gaCode;
	}

	public void setGaCode(String gaCode) {
		this.gaCode = gaCode;
	}
	@Column(name = "QUESTION")
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}
	@Column(name = "ANSWER")
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}
	@Column(name = "SEX", length=1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIRTHDAY", length=7)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REG_TIME", length=7)
	public Date getRegTime() {
		return this.regTime;
	}

	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}
	@Column(name = "LAST_LOGIN_FAILED", precision=10, scale=0)
	public Long getLastLoginFailed() {
		return this.lastLoginFailed;
	}

	public void setLastLoginFailed(Long lastLoginFailed) {
		this.lastLoginFailed = lastLoginFailed;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_TIME", length=7)
	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}
	@Column(name = "LAST_IP", length=15)
	public String getLastIp() {
		return this.lastIp;
	}

	public void setLastIp(String lastIp) {
		this.lastIp = lastIp;
	}
	@Column(name = "MSN", length=60)
	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}
	@Column(name = "QQ", length=20)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}
	@Column(name = "OFFICE_PHONE", length=20)
	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}
	@Column(name = "HOME_PHONE", length=20)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}
	@Column(name = "CHECKED", nullable = false, length=1)
	public String getChecked() {
		return this.checked;
	}

	public void setChecked(String checked) {
		this.checked = checked;
	}
	@Column(name = "AGE", length=60)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}
	@Column(name = "OPERATORS", length=60)
	public String getOperators() {
		return this.operators;
	}

	public void setOperators(String operators) {
		this.operators = operators;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PASSWORD_SET_DATE", length=7)
	public Date getPasswordSetDate() {
		return this.passwordSetDate;
	}

	public void setPasswordSetDate(Date passwordSetDate) {
		this.passwordSetDate = passwordSetDate;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PASSWORD_EXPIRE_DATE", length=7)
	public Date getPasswordExpireDate() {
		return this.passwordExpireDate;
	}

	public void setPasswordExpireDate(Date passwordExpireDate) {
		this.passwordExpireDate = passwordExpireDate;
	}
	@Column(name = "ADDRESS", length=60)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	@Column(name = "POSTCODE", length=6)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}
	@Column(name = "VALID_STATUS", length=1)
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERT_TIME_FOR_HIS",insertable = false, updatable = false)
	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OPERATE_TIME_FOR_HIS",insertable = false)
	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
}
