package ins.platform.saa.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * Vo Base Class of PO SaaFactor
 */ 
public class SaaFactorVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String factorCode;
	private Integer version;
	private String factorDesc;
	private String dataType;
	private Date insertTimeForHis;
	private Date operateTimeForHis;
	private List<SaaUserPowerVo> saaUserPowers = new ArrayList<SaaUserPowerVo>(0);
	private List<SaaFactorFieldVo> saaFactorFields = new ArrayList<SaaFactorFieldVo>(0);

    protected SaaFactorVoBase() {
	
    }

    
	public String getFactorCode() {
		return this.factorCode;
	}

	public void setFactorCode(String factorCode) {
		this.factorCode = factorCode;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getFactorDesc() {
		return this.factorDesc;
	}

	public void setFactorDesc(String factorDesc) {
		this.factorDesc = factorDesc;
	}

	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	public List<SaaUserPowerVo> getSaaUserPowers() {
		return this.saaUserPowers;
	}

	public void setSaaUserPowers(List<SaaUserPowerVo> saaUserPowers) {
		this.saaUserPowers = saaUserPowers;
	}

	public List<SaaFactorFieldVo> getSaaFactorFields() {
		return this.saaFactorFields;
	}

	public void setSaaFactorFields(List<SaaFactorFieldVo> saaFactorFields) {
		this.saaFactorFields = saaFactorFields;
	}
}
