package ins.platform.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;


/**
 * Vo Base Class of PO ImsCheckDetail
 */ 
public class ImsCheckDetailVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Integer version;
	private String userCode;
	private Date workDay;
	private String checkType;
	private String checkInAddress;
	private Date checkInTime;
	private String checkInReason;
	private String checkOutAddress;
	private Date checkOutTime;
	private String checkOutReason;
	private Date insertTimeForHis;
	private Date operateTimeForHis;

    protected ImsCheckDetailVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public Date getWorkDay() {
		return this.workDay;
	}

	public void setWorkDay(Date workDay) {
		this.workDay = workDay;
	}

	public String getCheckType() {
		return this.checkType;
	}

	public void setCheckType(String checkType) {
		this.checkType = checkType;
	}

	public String getCheckInAddress() {
		return this.checkInAddress;
	}

	public void setCheckInAddress(String checkInAddress) {
		this.checkInAddress = checkInAddress;
	}

	public Date getCheckInTime() {
		return this.checkInTime;
	}

	public void setCheckInTime(Date checkInTime) {
		this.checkInTime = checkInTime;
	}

	public String getCheckInReason() {
		return this.checkInReason;
	}

	public void setCheckInReason(String checkInReason) {
		this.checkInReason = checkInReason;
	}

	public String getCheckOutAddress() {
		return this.checkOutAddress;
	}

	public void setCheckOutAddress(String checkOutAddress) {
		this.checkOutAddress = checkOutAddress;
	}

	public Date getCheckOutTime() {
		return this.checkOutTime;
	}

	public void setCheckOutTime(Date checkOutTime) {
		this.checkOutTime = checkOutTime;
	}

	public String getCheckOutReason() {
		return this.checkOutReason;
	}

	public void setCheckOutReason(String checkOutReason) {
		this.checkOutReason = checkOutReason;
	}

	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
}
