package ins.platform.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * Vo Base Class of PO SddType
 */ 
public class SddTypeVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String type;
	private Integer version;
	private String typeDesc;
	private String newType;
	private String validStatus;
	private String flag;
	private Date insertTimeForHis;
	private Date operateTimeForHis;
	private List<SddCodeVo> sddCodes = new ArrayList<SddCodeVo>(0);

    protected SddTypeVoBase() {
	
    }

    
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getTypeDesc() {
		return this.typeDesc;
	}

	public void setTypeDesc(String typeDesc) {
		this.typeDesc = typeDesc;
	}

	public String getNewType() {
		return this.newType;
	}

	public void setNewType(String newType) {
		this.newType = newType;
	}

	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	public List<SddCodeVo> getSddCodes() {
		return this.sddCodes;
	}

	public void setSddCodes(List<SddCodeVo> sddCodes) {
		this.sddCodes = sddCodes;
	}
}
