package ins.platform.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;


/**
 * Vo Base Class of PO SmcMenu
 */ 
public class SmcMenuVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Integer version;
	private Long upperId;
	private Integer menuLevel;
	private String systemCode;
	private String menuCName;
	private String menuTName;
	private String menuEName;
	private String actionURL;
	private String target;
	private Integer displayNo;
	private String image;
	private String imageExpand;
	private String imageCollapse;
	private String iconExpand;
	private String iconCollapse;
	private String taskCode;
	private String creatorCode;
	private Date createTime;
	private String updaterCode;
	private Date updateTime;
	private String validInd;
	private String remark;
	private String flag;
	private Date insertTimeForHis;
	private Date operateTimeForHis;
	private String style;

    protected SmcMenuVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Long getUpperId() {
		return this.upperId;
	}

	public void setUpperId(Long upperId) {
		this.upperId = upperId;
	}

	public Integer getMenuLevel() {
		return this.menuLevel;
	}

	public void setMenuLevel(Integer menuLevel) {
		this.menuLevel = menuLevel;
	}

	public String getSystemCode() {
		return this.systemCode;
	}

	public void setSystemCode(String systemCode) {
		this.systemCode = systemCode;
	}

	public String getMenuCName() {
		return this.menuCName;
	}

	public void setMenuCName(String menuCName) {
		this.menuCName = menuCName;
	}

	public String getMenuTName() {
		return this.menuTName;
	}

	public void setMenuTName(String menuTName) {
		this.menuTName = menuTName;
	}

	public String getMenuEName() {
		return this.menuEName;
	}

	public void setMenuEName(String menuEName) {
		this.menuEName = menuEName;
	}

	public String getActionURL() {
		return this.actionURL;
	}

	public void setActionURL(String actionURL) {
		this.actionURL = actionURL;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public Integer getDisplayNo() {
		return this.displayNo;
	}

	public void setDisplayNo(Integer displayNo) {
		this.displayNo = displayNo;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getImageExpand() {
		return this.imageExpand;
	}

	public void setImageExpand(String imageExpand) {
		this.imageExpand = imageExpand;
	}

	public String getImageCollapse() {
		return this.imageCollapse;
	}

	public void setImageCollapse(String imageCollapse) {
		this.imageCollapse = imageCollapse;
	}

	public String getIconExpand() {
		return this.iconExpand;
	}

	public void setIconExpand(String iconExpand) {
		this.iconExpand = iconExpand;
	}

	public String getIconCollapse() {
		return this.iconCollapse;
	}

	public void setIconCollapse(String iconCollapse) {
		this.iconCollapse = iconCollapse;
	}

	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	public String getCreatorCode() {
		return this.creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdaterCode() {
		return this.updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getValidInd() {
		return this.validInd;
	}

	public void setValidInd(String validInd) {
		this.validInd = validInd;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}

	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}
}
