package ins.platform.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;


/**
 * Vo Base Class of PO SysAreaDict
 */ 
public class SysAreaDictVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String areaCode;
	private String areaName;
	private String shortCode;
	private String fullName;
	private BigDecimal areaLevel;
	private Short serialNo;
	private String upperCode;
	private String postCode;
	private String isValid;
	private String remark;
	private String oftenFlag;

    protected SysAreaDictVoBase() {
	
    }

    
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public String getShortCode() {
		return this.shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public BigDecimal getAreaLevel() {
		return this.areaLevel;
	}

	public void setAreaLevel(BigDecimal areaLevel) {
		this.areaLevel = areaLevel;
	}

	public Short getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Short serialNo) {
		this.serialNo = serialNo;
	}

	public String getUpperCode() {
		return this.upperCode;
	}

	public void setUpperCode(String upperCode) {
		this.upperCode = upperCode;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getIsValid() {
		return this.isValid;
	}

	public void setIsValid(String isValid) {
		this.isValid = isValid;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getOftenFlag() {
		return this.oftenFlag;
	}

	public void setOftenFlag(String oftenFlag) {
		this.oftenFlag = oftenFlag;
	}
}
