package ins.platform.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!


/**
 * Vo Base Class of PO SysCodeDictId
 */ 
public class SysCodeDictIdVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String codeType;
	private String codeCode;

    protected SysCodeDictIdVoBase() {
	
    }

    
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	public String getCodeCode() {
		return this.codeCode;
	}

	public void setCodeCode(String codeCode) {
		this.codeCode = codeCode;
	}
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		
		if (!(other instanceof SysCodeDictIdVo)) {
			return false;
		}
		SysCodeDictIdVo castOther = (SysCodeDictIdVo) other;  
		return ( (this.getCodeType()==castOther.getCodeType()) || ( this.getCodeType()!=null && castOther.getCodeType()!=null && this.getCodeType().equals(castOther.getCodeType()) ) )
 && ( (this.getCodeCode()==castOther.getCodeCode()) || ( this.getCodeCode()!=null && castOther.getCodeCode()!=null && this.getCodeCode().equals(castOther.getCodeCode()) ) );
	}
   
	public int hashCode() {
		int result = 17;         
		result = 37 * result + ( getCodeType() == null ? 0 : this.getCodeType().hashCode() );
		result = 37 * result + ( getCodeCode() == null ? 0 : this.getCodeCode().hashCode() );
		return result;
   }   
}
