package ins.platform.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;


/**
 * Vo Base Class of PO SysCompany
 */ 
public class SysCompanyVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String comCode;
	private String comPath;
	private String comCName;
	private String comEName;
	private String addressCName;
	private String addressEName;
	private String postCode;
	private String phoneNumber;
	private String faxNumber;
	private String upperComCode;
	private String insurerName;
	private String comType;
	private String manager;
	private String accountant;
	private String remark;
	private String newComCode;
	private String validStatus;
	private String acntUnit;
	private String articleCode;
	private String flag;
	private Date insertTimeForHis;
	private Date operateTimeForHis;

    protected SysCompanyVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getComPath() {
		return this.comPath;
	}

	public void setComPath(String comPath) {
		this.comPath = comPath;
	}

	public String getComCName() {
		return this.comCName;
	}

	public void setComCName(String comCName) {
		this.comCName = comCName;
	}

	public String getComEName() {
		return this.comEName;
	}

	public void setComEName(String comEName) {
		this.comEName = comEName;
	}

	public String getAddressCName() {
		return this.addressCName;
	}

	public void setAddressCName(String addressCName) {
		this.addressCName = addressCName;
	}

	public String getAddressEName() {
		return this.addressEName;
	}

	public void setAddressEName(String addressEName) {
		this.addressEName = addressEName;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	public String getUpperComCode() {
		return this.upperComCode;
	}

	public void setUpperComCode(String upperComCode) {
		this.upperComCode = upperComCode;
	}

	public String getInsurerName() {
		return this.insurerName;
	}

	public void setInsurerName(String insurerName) {
		this.insurerName = insurerName;
	}

	public String getComType() {
		return this.comType;
	}

	public void setComType(String comType) {
		this.comType = comType;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getAccountant() {
		return this.accountant;
	}

	public void setAccountant(String accountant) {
		this.accountant = accountant;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getNewComCode() {
		return this.newComCode;
	}

	public void setNewComCode(String newComCode) {
		this.newComCode = newComCode;
	}

	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getAcntUnit() {
		return this.acntUnit;
	}

	public void setAcntUnit(String acntUnit) {
		this.acntUnit = acntUnit;
	}

	public String getArticleCode() {
		return this.articleCode;
	}

	public void setArticleCode(String articleCode) {
		this.articleCode = articleCode;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Date getInsertTimeForHis() {
		return this.insertTimeForHis;
	}

	public void setInsertTimeForHis(Date insertTimeForHis) {
		this.insertTimeForHis = insertTimeForHis;
	}

	public Date getOperateTimeForHis() {
		return this.operateTimeForHis;
	}

	public void setOperateTimeForHis(Date operateTimeForHis) {
		this.operateTimeForHis = operateTimeForHis;
	}
}
