package ins.platform.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!


/**
 * Vo Base Class of PO SysCompanyUserId
 */ 
public class SysCompanyUserIdVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long userId;
	private Long groupID;

    protected SysCompanyUserIdVoBase() {
	
    }

    
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getGroupID() {
		return this.groupID;
	}

	public void setGroupID(Long groupID) {
		this.groupID = groupID;
	}
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		
		if (!(other instanceof SysCompanyUserIdVo)) {
			return false;
		}
		SysCompanyUserIdVo castOther = (SysCompanyUserIdVo) other;  
		return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getGroupID()==castOther.getGroupID()) || ( this.getGroupID()!=null && castOther.getGroupID()!=null && this.getGroupID().equals(castOther.getGroupID()) ) );
	}
   
	public int hashCode() {
		int result = 17;         
		result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
		result = 37 * result + ( getGroupID() == null ? 0 : this.getGroupID().hashCode() );
		return result;
   }   
}
