package ins.platform.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!


/**
 * Vo Base Class of PO SysCompanyUser
 */ 
public class SysCompanyUserVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private SysCompanyUserIdVo id;

    protected SysCompanyUserVoBase() {
	
    }

    
	public SysCompanyUserIdVo getId() {
		return this.id;
	}

	public void setId(SysCompanyUserIdVo id) {
		this.id = id;
	}
}
