drop table ims_check_detail cascade constraints;
drop table msg_info cascade constraints;
drop table msg_info_custom cascade constraints;
drop table msg_info_his cascade constraints;
drop table sdd_type cascade constraints;
drop table sdd_code cascade constraints;
drop table smc_menu cascade constraints;
drop table sta_letter cascade constraints;
drop table sys_application cascade constraints;
drop table sys_area_dict cascade constraints;
drop table sys_cas_login cascade constraints;
drop table sys_company cascade constraints;
drop table sys_company_user cascade constraints;
drop table sys_trans_config cascade constraints;
drop table sys_user cascade constraints;
drop table sys_user_property cascade constraints;
drop table sys_user_run_as cascade constraints;
drop table PDFC_SERVER cascade constraints;
drop sequence seq_sys_user_run_as;
drop sequence seq_sys_user_property;
drop sequence seq_sys_user;
drop sequence seq_sys_company;
drop sequence seq_sys_cas_login;
drop sequence seq_sys_application;
drop sequence seq_sta_letter;
drop sequence seq_smc_menu;
drop sequence seq_sdd_code;
drop sequence seq_sdd_type;
drop sequence seq_msg_info_his;
drop sequence seq_msg_info_custom;
drop sequence seq_ims_check_detail;
drop sequence seq_msg_info;
drop sequence hibernate_sequence;