package ins.platform.oauth2.schema;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import static javax.persistence.GenerationType.SEQUENCE;

/**
 * POJO Class OauthClient
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "OAUTH_CLIENT")
public class OauthClient implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String clientId;
	private String clientSecret;
	private String redirectUri;
	@Id
	@Column(name = "CLIENT_ID", unique = true, nullable = false, length=80)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}
	@Column(name = "CLIENT_SECRET", nullable = false, length=80)
	public String getClientSecret() {
		return this.clientSecret;
	}

	public void setClientSecret(String clientSecret) {
		this.clientSecret = clientSecret;
	}
	@Column(name = "REDIRECT_URI", nullable = false, length=2000)
	public String getRedirectUri() {
		return this.redirectUri;
	}

	public void setRedirectUri(String redirectUri) {
		this.redirectUri = redirectUri;
	}
}
